# Generated by Django 3.1.5 on 2021-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Zdjęcie'),
        ),
    ]
